### PR TITLE
Tomahawk texture

### PR DESCRIPTION
**Pull request by Sunconure11**
Seeing if this is a good enough texture for a tomahawk, tell me what you think. It is created from infused sticks and chlorophyte. This is my attempt at texturing some of the items that were mentioned in the documents, but, have no textures yet. I tried to create a pipe tomahawk, but, that did not end up well, so, I tried as hard as I could.

### CODE REVIEW

**Comment by ljfa-ag** [comment]
Well many things for which there are textures are not actually implemented in the mod as far as I can see.
I guess I can accept this nonetheless, but please remove the Thumbs.db files first.

**Comment by Sunconure11** [comment]
I shall do that Ina bit

**Comment by Sunconure11** [comment]
*in a

**Comment by Sunconure11** [comment]
Also, those files had snuck in while making the request.

**Pull request merged**
